server:
  port: 8081
spring:
  application:
    name: example
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 128505Tan..
    type: com.alibaba.druid.pool.DruidDataSource